### ISSUE TITLE
Error when subscribing an email address

### ISSUE THREAD

**Issue by ghost** [BitBagCommerce/SyliusMailChimpPlugin#14]
Hello,

When trying to subscribe an email address, I have to following error:
```
The "bitbag_sylius_mailchimp_plugin.validator.email_validator" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```
I was able to fix it by adding `public: true` in `src/Resources/config/services.yml`:
```
services:
    bitbag_sylius_mailchimp_plugin.validator.email_validator:
        class: BitBag\SyliusMailChimpPlugin\Validator\NewsletterValidator
        public: true
        arguments:
            - "@validator"
            - "@sylius.manager.customer"
```
