### ISSUE TITLE
You have requested a non-existent parameter "mailchimp.api_key"

### ISSUE THREAD

**Issue by krystal25** [BitBagCommerce/SyliusMailChimpPlugin#27]
After installing the plugin, and setting the API keys in .env, I get the following error:

> You have requested a non-existent parameter "mailchimp.api_key"

I can see the parameters declared in vendor\bitbag\mailchimp-plugin\tests\Application\config\packages\_sylius.yaml_sylius.yaml

```
    mailchimp.api_key: '%env(resolve:MAIL_CHIMP_API_KEY)%'
    mailchimp.list_id: '%env(resolve:MAIL_CHIMP_LIST_ID)%'
```

and they are called in services.yml and contexts.yml

```
    bitbag_sylius_mailchimp_plugin.context.ui.shop.mailchimp:
        class: Tests\BitBag\SyliusMailChimpPlugin\Behat\Context\Ui\Shop\MailChimpContext
        arguments:
            - "@sylius.behat.shared_storage"
            - "%mailchimp.api_key%"
            - "%mailchimp.list_id%"
```

So why does it say it does not exist? If I replace `%mailchimp.api_key%` with the actual key, it works, but I do not want that as I need the key to be taken from .env
