### ISSUE TITLE
 You have requested a non-existent parameter "mailchimp.api_key"

### ISSUE THREAD

**Issue by luckylucciano** [BitBagCommerce/SyliusMailChimpPlugin#31]
Hello all,

Cannot install mailchimp-plugin, and same error, i ' ve not understood the solution before:

"You must add a parameter to your _sylius.yaml file in your project"

Need help...

**Comment by Florian-Merle** [comment]
In your `_sylius.yaml` file, add the follwing parameters:

```yaml
parameters:
    mailchimp.api_key: '%env(resolve:MAIL_CHIMP_API_KEY)%'
    mailchimp.list_id: '%env(resolve:MAIL_CHIMP_LIST_ID)%'
```
